CREATE TYPE activity_label AS ENUM (
  'Dining',
  'Landmark',
  'Recreation',
  'Night-life',
  'Educational'
);

--CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE activities (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  created_ts TIMESTAMP DEFAULT now() NOT NULL,
  content TEXT,
  label activity_label,
  --rating star_rating NOT NULL,
  voyage_id INTEGER
    REFERENCES voyages(id) ON DELETE CASCADE NOT NULL
);